### ISSUE TITLE
get rid of `_MinimalHIToolbox` once PyObjC 11.1 is out

### ISSUE THREAD

**Issue by glyph** [glyph/QuickMacHotKey#7]
It looks like it will no longer be necessary, as PyObjC 11 is going to have the relevant minimal carbon bindings built in: https://github.com/ronaldoussoren/pyobjc/issues/249

**Comment by appenz** [comment]
Any chance you are planning to update this? I am using it and right now for me it throws a nasty deprecation warning about the use of _MinimalHIToolbox.

**Comment by glyph** [comment]
Hmm. Looks like the upstream issue is still open, despite the aforementioned release having been published. I will have to investigate.

**Comment by appenz** [comment]
Oh, you are right that it is. The warning that is generated (below) is also
a bit outdated (this is with PyObjc 11.0). We may have to wait.

  Guido

------------------------------
=====================================================================
warnings summary
=====================================================================
.
venv/lib/python3.13/site-packages/quickmachotkey/_MinimalHIToolbox/__init__.py:17
  /
Users/gappenzeller/dev/myprojects/macLLM/.venv/lib/python3.13/site-packages/quickmachotkey/_MinimalHIToolbox/__init__.py:17
<http://users/gappenzeller/dev/myprojects/macLLM/.venv/lib/python3.13/site-packages/quickmachotkey/_MinimalHIToolbox/__init__.py:17>:
DeprecationWarning: This function will be removed in PyObjC 9, switch to
the modern metadata system
    __bundle__ = _objc.initFrameworkWrapper(

.venv/lib/python3.13/site-packages/objc/_bridgesupport.py:661
  /
Users/gappenzeller/dev/myprojects/macLLM/.venv/lib/python3.13/site-packages/objc/_bridgesupport.py:661
<http://users/gappenzeller/dev/myprojects/macLLM/.venv/lib/python3.13/site-packages/objc/_bridgesupport.py:661>:
DeprecationWarning: This function will be removed in PyObjC 10, switch to
the modern metadata system
    objc.parseBridgeSupport(data, globals, frameworkName, *args, **kwds)

**Comment by glyph** [comment]
Oh, I guess I'm overdue for a release here? Looks like the version on PyPI is still using `initFrameworkWrapper` when #6 already updated the project to "modern metadata". I'll do that now.

**Comment by glyph** [comment]
Currently:

```console
$ mktmpenv; pip install quickmachotkey; python -Werror -c 'import quickmachotkey'
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-7251953e0799200/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-7251953e0799200/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-7251953e0799200/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-7251953e0799200/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-7251953e0799200/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
Looking in indexes: http://127.0.0.1:3141/root/pypi/+simple/
Collecting quickmachotkey
  Downloading http://127.0.0.1:3141/root/pypi/%2Bf/d20/6c558ed308784/quickmachotkey-2023.11.17-py3-none-any.whl (9.9 kB)
Collecting pyobjc-core (from quickmachotkey)
  Downloading http://127.0.0.1:3141/root/pypi/%2Bf/189/86f83998fbd5d/pyobjc_core-11.1-cp313-cp313-macosx_10_13_universal2.whl (676 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.4/676.4 kB 3.4 GB/s eta 0:00:00
Installing collected packages: pyobjc-core, quickmachotkey
Successfully installed pyobjc-core-11.1 quickmachotkey-2023.11.17
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import quickmachotkey
  File "/Users/glyph/.virtualenvs/tmp-7251953e0799200/lib/python3.13/site-packages/quickmachotkey/__init__.py", line 11, in <module>
    from ._MinimalHIToolbox import (
    ...<14 lines>...
    )
  File "/Users/glyph/.virtualenvs/tmp-7251953e0799200/lib/python3.13/site-packages/quickmachotkey/_MinimalHIToolbox/__init__.py", line 17, in <module>
    __bundle__ = _objc.initFrameworkWrapper(
        __name__,
    ...<6 lines>...
        globals=globals(),
    )
  File "/Users/glyph/.virtualenvs/tmp-7251953e0799200/lib/python3.13/site-packages/objc/_bridgesupport.py", line 712, in initFrameworkWrapper
    warnings.warn(
    ~~~~~~~~~~~~~^
        "This function will be removed in PyObjC 9, switch to the modern metadata system",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        DeprecationWarning,
        ^^^^^^^^^^^^^^^^^^^
        stacklevel=2,
        ^^^^^^^^^^^^^
    )
    ^
DeprecationWarning: This function will be removed in PyObjC 9, switch to the modern metadata system
```

**Comment by glyph** [comment]
on `trunk`:
```console
$ python -Werror -c 'import quickmachotkey'
$
```

**Comment by glyph** [comment]
@appenz Try out https://pypi.org/project/quickmachotkey/2025.7.28/ and let me know if your issue is fixed; it seems to address the warning for me.

**Comment by appenz** [comment]
Amazing. Give me 48 hours and I'll report back.

**Comment by appenz** [comment]
Tested and this fixes the warning. Wohoo! Thank you so much, and let me
know if there is any opportunity to buy you a coffee!

**Comment by glyph** [comment]
> let me know if there is any opportunity to buy you a coffee!

The opportunities abound :)

- https://www.patreon.com/creatorglyph
- https://github.com/sponsors/glyph
- https://ko-fi.com/creatorglyph

depending on your preference :)

**Comment by appenz** [comment]
Done. Thank you again!
